## Colors configuration
[colors.primary]
background = "#00191F"
foreground = "#d8f6f1"

[colors.normal]
black   = "#00191F"
red     = "#88B9D9"
green   = "#94C5DA"
yellow  = "#9DD2FD"
blue    = "#AADAFE"
magenta = "#B8EAFB"
cyan    = "#C1FFF4"
white   = "#d8f6f1"

[colors.bright]
black   = "#97aca8"
red     = "#88B9D9"
green   = "#94C5DA"
yellow  = "#9DD2FD"
blue    = "#AADAFE"
magenta = "#B8EAFB"
cyan    = "#C1FFF4"
white   = "#d8f6f1"
