## Colors configuration
[colors.primary]
background = "#010915"
foreground = "#bcb0d3"

[colors.normal]
black   = "#010915"
red     = "#2F417C"
green   = "#313E85"
yellow  = "#374488"
blue    = "#3C649C"
magenta = "#4F4C94"
cyan    = "#6458A1"
white   = "#bcb0d3"

[colors.bright]
black   = "#837b93"
red     = "#2F417C"
green   = "#313E85"
yellow  = "#374488"
blue    = "#3C649C"
magenta = "#4F4C94"
cyan    = "#6458A1"
white   = "#bcb0d3"
