# Shell variables
# Generated by 'wal'
wallpaper='/home/bist/Pictures/wallpapers/wide_alien_planet.jpeg'

# Special
background='#030308'
foreground='#f6f5f3'
cursor='#f6f5f3'

# Colors
color0='#030308'
color1='#C0599E'
color2='#3DAAAA'
color3='#A3A2A0'
color4='#DDBCAF'
color5='#EDD7CE'
color6='#FAE7D8'
color7='#f6f5f3'
color8='#acabaa'
color9='#C0599E'
color10='#3DAAAA'
color11='#A3A2A0'
color12='#DDBCAF'
color13='#EDD7CE'
color14='#FAE7D8'
color15='#f6f5f3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
