# Shell variables
# Generated by 'wal'
wallpaper='/home/bist/Pictures/wallpapers/light-ring.jpg'

# Special
background='#010915'
foreground='#bcb0d3'
cursor='#bcb0d3'

# Colors
color0='#010915'
color1='#2F417C'
color2='#313E85'
color3='#374488'
color4='#3C649C'
color5='#4F4C94'
color6='#6458A1'
color7='#bcb0d3'
color8='#837b93'
color9='#2F417C'
color10='#313E85'
color11='#374488'
color12='#3C649C'
color13='#4F4C94'
color14='#6458A1'
color15='#bcb0d3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
