# Shell variables
# Generated by 'wal'
wallpaper='/home/bist/Pictures/wallpapers/forest-bridge.jpg'

# Special
background='#00191F'
foreground='#d8f6f1'
cursor='#d8f6f1'

# Colors
color0='#00191F'
color1='#88B9D9'
color2='#94C5DA'
color3='#9DD2FD'
color4='#AADAFE'
color5='#B8EAFB'
color6='#C1FFF4'
color7='#d8f6f1'
color8='#97aca8'
color9='#88B9D9'
color10='#94C5DA'
color11='#9DD2FD'
color12='#AADAFE'
color13='#B8EAFB'
color14='#C1FFF4'
color15='#d8f6f1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
